### ISSUE TITLE
Rfrac Values determined as Negative on SATP3 Mv35 (So4 

### ISSUE THREAD

**Issue by samdayweiss** [simonsobs/sodetlib#443]
@jlashner @msilvafe 
A few days ago on BL11 and BL10 of SO4 slot3 (Mv35, ws2) started showing a lower bias step yield. This was noticed after hammering due to inability to relock on September 24th. Hammering again did not fix the problem, so I did some investigation. I discovered that IV yield tracked bias step yield (was also low), but did not track with bias tickle yield (which was still high, so likely not a tracking issue).

I hammered the slot again on the 26th of september and the issue was seemingly resolved. Looking carefully at an example bias step analysis during the problem period, I noticed a large number of detectors assigned negative Rfrac values (see plot attached, for BL11 on Mv35). 

In this npy you will see that for the negative Rfrac values, the R_n_IV values also look weird, but, tau_eff estimates look normal. I stopped investigating there to make this post but maybe someone can pick up the troubleshooting effort.

My worry is that, across all UFMs, detectors that are actually working are being assigned negative bias step values, which will inevitably be cut in the map making pipeline.

Path to this bias step analysis file on So4: `/data/smurf_data/20240926/ufm_mv35/1727366255/outputs/1727367015_bias_step_analysis.npy`
![Screenshot 2024-09-26 at 4 39 59 PM](https://github.com/user-attachments/assets/377b23d2-1c6d-4adb-a270-e7e989a7024c)

**Comment by jlashner** [comment]
Ok I know what the issue is here. 

Looking at the TODs, the bias steps look great, however the IV is upsidown so the measured Rn is negative.
![image](https://github.com/user-attachments/assets/3474ac47-b6e9-48f6-8840-871253fe5c6d)

This happens if you attempt to take an IV after relocking without taking a bg-map in between. The bg-map is important, for determining the channel to bias line mapping, but also for determining the "detector polarity" with respect to changes in the bias line. I'm not exactly sure why, but the polarity can change when you re-tune or re-lock (I think it has to do with the measured eta parameter, but am not sure). So its really important you take a bgmap after every relock before doing any other operations.

Looking at your pysmurf action history, it looks like you're not doing this, so that is what is causing the negative resistances for some channels shown above. 

![image](https://github.com/user-attachments/assets/96a0e733-dcf3-4580-bbbf-147e9ce57181)
